import Head from "next/head";
import TestWrapper from "../components/TestWrapper";
import { useAppState } from "../contexts/state";

export default function Home() {
  const { selectedGamer, setSelectedGamer, selectedRaid, setSelectedRaid } =
    useAppState();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <p>Index: {selectedRaid}</p>
        <p>Index: {selectedGamer}</p>
        <TestWrapper />
      </div>
    </>
  );
}
